#!/usr/bin/env bash

# Publish pdoc documentation for GitHub Pages.

TEMP=`mktemp -d`
mkdir -p docs

# create pages for modules
pdoc --config sort_identifiers=False --config show_inherited_members=True --html -o $TEMP tikz
mv $TEMP/tikz docs/

# create file that tells GitHub to just copy the files
touch docs/.nojekyll
