#!/usr/bin/env bash

# Publish Sphinx documentation for GitHub Pages.

# delete old version
rm -r ../docs/
# generate new version, putting the html files into the repository's `docs`
# folder, but the cached build information under `_build`.
sphinx-build -b html ./ ../docs/ -d ./_build/
# create file that tells GitHub to just copy the files
touch ../docs/.nojekyll
